// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfgUEbI_RMhf_apA1Air3k0JkuDslFXHY',
    appId: '1:47394972227:web:733a3d473921bee8bfeaf6',
    messagingSenderId: '47394972227',
    projectId: 'build-solution-9d13f',
    authDomain: 'build-solution-9d13f.firebaseapp.com',
    storageBucket: 'build-solution-9d13f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLhJLlMlXER5yDvh_GQJZUOPV8Nw1jl8A',
    appId: '1:47394972227:android:7c5aaffe07a8ecc3bfeaf6',
    messagingSenderId: '47394972227',
    projectId: 'build-solution-9d13f',
    storageBucket: 'build-solution-9d13f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMbC48gwVcjzrNaHZo_ZfLuAjg7oHBBiQ',
    appId: '1:47394972227:ios:3e98da00dba8bfb2bfeaf6',
    messagingSenderId: '47394972227',
    projectId: 'build-solution-9d13f',
    storageBucket: 'build-solution-9d13f.appspot.com',
    iosClientId: '47394972227-f2j7d6nlsvrsjt793o7fht9kno9kf3ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildSolution',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMbC48gwVcjzrNaHZo_ZfLuAjg7oHBBiQ',
    appId: '1:47394972227:ios:3e98da00dba8bfb2bfeaf6',
    messagingSenderId: '47394972227',
    projectId: 'build-solution-9d13f',
    storageBucket: 'build-solution-9d13f.appspot.com',
    iosClientId: '47394972227-f2j7d6nlsvrsjt793o7fht9kno9kf3ki.apps.googleusercontent.com',
    iosBundleId: 'com.example.buildSolution',
  );
}
